/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin;

import Business.VendorDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ujjval
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form adminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private VendorDirectory vendorList;

    public AdminWorkAreaJPanel(JPanel userProcessContainer, VendorDirectory vendorList) {
        initComponents();
        this.vendorList = vendorList;
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddVendor = new javax.swing.JButton();
        btnViewVendor = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Welcom Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 21, -1, -1));

        btnAddVendor.setText("Add Vendor");
        btnAddVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVendorActionPerformed(evt);
            }
        });
        add(btnAddVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 112, -1, -1));

        btnViewVendor.setText("View Vendors");
        btnViewVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVendorActionPerformed(evt);
            }
        });
        add(btnViewVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 112, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVendorActionPerformed
        // TODO add your handling code here:
        VendorAddJPanel vendorAddPanel = new VendorAddJPanel(userProcessContainer, vendorList);
        userProcessContainer.add("VendorAddJPanel", vendorAddPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddVendorActionPerformed

    private void btnViewVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVendorActionPerformed
        // TODO add your handling code here:
        VendorViewJPanel vendorViewPanel = new VendorViewJPanel(userProcessContainer, vendorList);
        userProcessContainer.add("VendorViewJPanel", vendorViewPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewVendorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVendor;
    private javax.swing.JButton btnViewVendor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
