/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin;

import Business.Vendor;
import Business.VendorDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Ujjval
 */
public class VendorViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VendorViewJPanel
     */
    private JPanel userProcessContainer;
    private VendorDirectory vendorList;

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblVendor.getModel();
        dtm.setRowCount(0); // Empties the table
        for (Vendor v : vendorList.getVendorList()) {
            Object row[] = new Object[2];
            row[0] = v;
            row[1] = v.getId();
            dtm.addRow(row);
        }
        
    }

    public VendorViewJPanel(JPanel userProcessContainer, VendorDirectory vendorList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.vendorList = vendorList;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        tblVendorJScrollPane = new javax.swing.JScrollPane();
        tblVendor = new javax.swing.JTable();
        btnViewVendor = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtSearchByName = new javax.swing.JTextField();
        btnSearchVendor = new javax.swing.JButton();
        btnDeleteVendor = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setText("Vendors List");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 11, -1, -1));

        tblVendor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendor Name", "Vendor ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVendorJScrollPane.setViewportView(tblVendor);

        add(tblVendorJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 43, 337, 123));

        btnViewVendor.setText("View Vendor");
        btnViewVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVendorActionPerformed(evt);
            }
        });
        add(btnViewVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 192, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 288, -1, -1));
        add(txtSearchByName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 234, 132, -1));

        btnSearchVendor.setText("View by Name>>");
        btnSearchVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchVendorActionPerformed(evt);
            }
        });
        add(btnSearchVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 233, -1, -1));

        btnDeleteVendor.setText("Delete Vendor");
        btnDeleteVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVendorActionPerformed(evt);
            }
        });
        add(btnDeleteVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 192, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVendorActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblVendor.getSelectedRow();
        if (selectedRow >= 0) {
            Vendor v = (Vendor) tblVendor.getValueAt(selectedRow, 0);
            ViewVendorJPanel panel = new ViewVendorJPanel(userProcessContainer, v);
            userProcessContainer.add("ViewVendorJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnViewVendorActionPerformed

    private void btnSearchVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchVendorActionPerformed
        // TODO add your handling code here:
        if (txtSearchByName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Vendor Name!!");
        } else {
            Vendor v = vendorList.searchVendor(txtSearchByName.getText());
            if (v == null) {
                JOptionPane.showMessageDialog(this, "The Vendor name does not exists!!", "Information", JOptionPane.INFORMATION_MESSAGE);
            } else {
                ViewVendorJPanel panel = new ViewVendorJPanel(userProcessContainer, v);
                userProcessContainer.add("ViewVendorJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
    }//GEN-LAST:event_btnSearchVendorActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVendorActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVendor.getSelectedRow();
        if (selectedRow >= 0) {
            int result = JOptionPane.showConfirmDialog(this, "Confirm Delete?", "Warning", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                 Vendor v = (Vendor) tblVendor.getValueAt(selectedRow, 0);
                vendorList.deleteVendor(v);
                JOptionPane.showMessageDialog(this, "Selected Vendor has been Deleted!");
                populateTable();
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnDeleteVendorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteVendor;
    private javax.swing.JButton btnSearchVendor;
    private javax.swing.JButton btnViewVendor;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTable tblVendor;
    private javax.swing.JScrollPane tblVendorJScrollPane;
    private javax.swing.JTextField txtSearchByName;
    // End of variables declaration//GEN-END:variables
}
