/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin;

import Business.Vendor;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ujjval
 */
public class ViewVendorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVendorJPanel
     */
    JPanel userProcessContainer;
    Vendor v;

    public ViewVendorJPanel(JPanel userProcessContainer, Vendor v) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.v = v;
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        txtVendorName.setText(v.getName());
        txtVendorID.setText(v.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblVendorName = new javax.swing.JLabel();
        lblVendorID = new javax.swing.JLabel();
        txtVendorName = new javax.swing.JTextField();
        txtVendorID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setText("View Vendor");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 11, -1, -1));

        lblVendorName.setText("Vendor Name:");
        add(lblVendorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 70, -1, -1));

        lblVendorID.setText("Vendor ID:");
        add(lblVendorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 112, -1, -1));

        txtVendorName.setEditable(false);
        add(txtVendorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 67, 165, -1));

        txtVendorID.setEditable(false);
        add(txtVendorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 109, 165, -1));

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 159, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 159, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 159, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtVendorID.setEditable(true);
        txtVendorName.setEditable(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtVendorID.getText().isEmpty() || txtVendorName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter details of all the fields!!");
        } else {
            v.setId(txtVendorID.getText());
            v.setName(txtVendorName.getText());
            btnSave.setEnabled(false);
            btnUpdate.setEnabled(true);
            txtVendorID.setEditable(false);
            txtVendorName.setEditable(false);
            JOptionPane.showMessageDialog(this, "Vendor details Updated successfully!!", "Information", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] compArray = userProcessContainer.getComponents();
        Component component = compArray[compArray.length - 1];
        VendorViewJPanel panel = (VendorViewJPanel) component;
        panel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblVendorID;
    private javax.swing.JLabel lblVendorName;
    private javax.swing.JTextField txtVendorID;
    private javax.swing.JTextField txtVendorName;
    // End of variables declaration//GEN-END:variables
}
