/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Resume;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Ujjval
 */
public class CreateResumeJpanel extends javax.swing.JPanel {

    /**
     * Creates new form createResumeJpanel
     */
    private Resume resume;
    public CreateResumeJpanel(Resume recvdResume) {
        initComponents();
        this.resume=recvdResume;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJLabel = new javax.swing.JLabel();
        firstNameJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        addrLine1JLabel = new javax.swing.JLabel();
        addrLine2JLabel = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();
        countryJLabel = new javax.swing.JLabel();
        zipJLabel = new javax.swing.JLabel();
        createResumeJbtn = new javax.swing.JButton();
        contactJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        skillTxtField = new javax.swing.JTextField();
        addrLine2TxtField = new javax.swing.JTextField();
        firstNameTxtField = new javax.swing.JTextField();
        addrLine1TxtField = new javax.swing.JTextField();
        cityTxtField = new javax.swing.JTextField();
        stateTxtField = new javax.swing.JTextField();
        zipTxtField = new javax.swing.JTextField();
        countryTxtField = new javax.swing.JTextField();
        emailTxtField = new javax.swing.JTextField();
        contactNumbTxtField = new javax.swing.JTextField();
        objectiveJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        objectiveJtextArea = new javax.swing.JTextArea();
        affiliationJLabel = new javax.swing.JLabel();
        affiliationJTextField = new javax.swing.JTextField();
        photoUploadJLabel = new javax.swing.JLabel();
        browseJbtn = new javax.swing.JButton();
        displayImagePathJLabel = new javax.swing.JLabel();
        educationJLabel = new javax.swing.JLabel();
        univJLabel = new javax.swing.JLabel();
        completionYearJLabel = new javax.swing.JLabel();
        majorJLabel = new javax.swing.JLabel();
        degreeTypeJLabel = new javax.swing.JLabel();
        degreeTypeJTextField = new javax.swing.JTextField();
        univNameJTextField = new javax.swing.JTextField();
        completionDateJTextField = new javax.swing.JTextField();
        majorJTextField = new javax.swing.JTextField();
        addressDetailsJLabel = new javax.swing.JLabel();
        skillJLabel = new javax.swing.JLabel();
        lastNameTxtField = new javax.swing.JTextField();
        achievementsJlabel = new javax.swing.JLabel();
        achievementJScrollPane = new javax.swing.JScrollPane();
        achievementsJTextArea = new javax.swing.JTextArea();
        gpaJLabel = new javax.swing.JLabel();
        gpaJTxtField = new javax.swing.JTextField();
        experienceJLabel = new javax.swing.JLabel();
        experienceJScrollPane = new javax.swing.JScrollPane();
        experienceJTextArea = new javax.swing.JTextArea();
        dobJLabel = new javax.swing.JLabel();
        dobJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerJLabel.setText("Create your Resume");
        add(headerJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        firstNameJLabel.setText("First Name:");
        add(firstNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 85, 82, -1));

        lastNameJLabel.setText("Last Name:");
        add(lastNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 82, -1));

        addrLine1JLabel.setText("Address Line1:");
        add(addrLine1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, -1));

        addrLine2JLabel.setText("Address Line2:");
        add(addrLine2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, -1));

        cityJLabel.setText("City:");
        add(cityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 82, -1));

        stateJLabel.setText("State:");
        add(stateJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 82, 20));

        countryJLabel.setText("Country:");
        add(countryJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 82, -1));

        zipJLabel.setText("Zip Code:");
        add(zipJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 82, -1));

        createResumeJbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createResumeJbtn.setText("Create Resume");
        createResumeJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createResumeJbtnActionPerformed(evt);
            }
        });
        add(createResumeJbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, -1, -1));

        contactJLabel.setText("Contact Number:");
        add(contactJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, 20));

        emailJLabel.setText("Email Id:");
        add(emailJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 82, -1));

        skillTxtField.setNextFocusableComponent(browseJbtn);
        add(skillTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 133, 150, -1));

        addrLine2TxtField.setNextFocusableComponent(cityTxtField);
        add(addrLine2TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 150, -1));

        firstNameTxtField.setNextFocusableComponent(lastNameTxtField);
        add(firstNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 81, 150, -1));

        addrLine1TxtField.setNextFocusableComponent(addrLine2TxtField);
        add(addrLine1TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, -1));

        cityTxtField.setNextFocusableComponent(stateTxtField);
        add(cityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 150, -1));

        stateTxtField.setNextFocusableComponent(countryTxtField);
        add(stateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 150, -1));

        zipTxtField.setNextFocusableComponent(contactNumbTxtField);
        add(zipTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 150, -1));

        countryTxtField.setNextFocusableComponent(zipTxtField);
        add(countryTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 150, -1));

        emailTxtField.setNextFocusableComponent(affiliationJTextField);
        add(emailTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 150, -1));

        contactNumbTxtField.setNextFocusableComponent(emailTxtField);
        add(contactNumbTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 150, -1));

        objectiveJLabel.setText("Objective Statement:");
        add(objectiveJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 110, -1, -1));

        objectiveJtextArea.setColumns(20);
        objectiveJtextArea.setLineWrap(true);
        objectiveJtextArea.setRows(5);
        objectiveJtextArea.setNextFocusableComponent(achievementsJTextArea);
        jScrollPane2.setViewportView(objectiveJtextArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 110, 370, 50));

        affiliationJLabel.setText("Affiliation:");
        add(affiliationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 84, -1, -1));

        affiliationJTextField.setNextFocusableComponent(objectiveJtextArea);
        add(affiliationJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 81, 370, -1));

        photoUploadJLabel.setText("Upload Photo:");
        add(photoUploadJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        browseJbtn.setText("Browse..");
        browseJbtn.setNextFocusableComponent(dobJTextField);
        browseJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseJbtnActionPerformed(evt);
            }
        });
        add(browseJbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));
        add(displayImagePathJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 276, 20));

        educationJLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Education Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        educationJLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                educationJLabelFocusLost(evt);
            }
        });
        add(educationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 500, 190));

        univJLabel.setText("University Name:");
        add(univJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        completionYearJLabel.setText("Date of completion:");
        add(completionYearJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        majorJLabel.setText("Major:");
        add(majorJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        degreeTypeJLabel.setText("Degree Type:");
        add(degreeTypeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

        degreeTypeJTextField.setText("(High School/Under Graduate/Graduate)..");
        degreeTypeJTextField.setNextFocusableComponent(gpaJTxtField);
        degreeTypeJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                degreeTypeJTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                degreeTypeJTextFieldFocusLost(evt);
            }
        });
        degreeTypeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeTypeJTextFieldActionPerformed(evt);
            }
        });
        add(degreeTypeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 240, -1));

        univNameJTextField.setNextFocusableComponent(completionDateJTextField);
        add(univNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 240, -1));

        completionDateJTextField.setText("(MM/DD/YYYY)");
        completionDateJTextField.setNextFocusableComponent(majorJTextField);
        completionDateJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                completionDateJTextFieldFocusGained(evt);
            }
        });
        completionDateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completionDateJTextFieldActionPerformed(evt);
            }
        });
        add(completionDateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 240, -1));

        majorJTextField.setNextFocusableComponent(degreeTypeJTextField);
        majorJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majorJTextFieldActionPerformed(evt);
            }
        });
        add(majorJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 240, -1));

        addressDetailsJLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Address Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        add(addressDetailsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 310, 280));

        skillJLabel.setText("Skills:");
        add(skillJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 135, -1, -1));

        lastNameTxtField.setNextFocusableComponent(skillTxtField);
        add(lastNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 107, 150, -1));

        achievementsJlabel.setText("Achievements:");
        add(achievementsJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 170, -1, -1));

        achievementsJTextArea.setColumns(20);
        achievementsJTextArea.setLineWrap(true);
        achievementsJTextArea.setRows(5);
        achievementsJTextArea.setNextFocusableComponent(experienceJTextArea);
        achievementJScrollPane.setViewportView(achievementsJTextArea);

        add(achievementJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 170, 370, 50));

        gpaJLabel.setText("GPA:");
        add(gpaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, -1));
        add(gpaJTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 240, -1));

        experienceJLabel.setText("Experience:");
        add(experienceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 230, -1, -1));

        experienceJTextArea.setColumns(20);
        experienceJTextArea.setRows(5);
        experienceJTextArea.setNextFocusableComponent(univNameJTextField);
        experienceJScrollPane.setViewportView(experienceJTextArea);

        add(experienceJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 230, 370, 70));

        dobJLabel.setText("Date Of Birth:");
        add(dobJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 222, -1, -1));

        dobJTextField.setNextFocusableComponent(addrLine1JLabel);
        add(dobJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createResumeJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createResumeJbtnActionPerformed
        // TODO add your handling code here:
        resume.setFirstName(firstNameTxtField.getText());
        resume.setLastName(lastNameTxtField.getText());
        resume.setAddressLine1(addrLine1TxtField.getText());
        resume.setAddressLine2(addrLine2TxtField.getText());
        resume.setCity(cityTxtField.getText());
        resume.setState(stateTxtField.getText());
        resume.setCountry(countryTxtField.getText());
        resume.setZipcode(zipTxtField.getText());
        resume.setContactNumb(contactNumbTxtField.getText());
        resume.setEmailId(emailTxtField.getText());
        resume.setObjectiveStatement(objectiveJtextArea.getText());
        resume.setAffiliation(affiliationJTextField.getText());
        resume.setUnivName(univNameJTextField.getText());
        resume.setDateOfCompletion(completionDateJTextField.getText());
        resume.setMajor(majorJTextField.getText());
        resume.setDegreeType(degreeTypeJTextField.getText());
        resume.setGpa(gpaJTxtField.getText());
        resume.setSkill(skillTxtField.getText());
        resume.setAchievements(achievementsJTextArea.getText());
        resume.setExperience(experienceJTextArea.getText());
        resume.setDob(dobJTextField.getText());
        JOptionPane.showMessageDialog(null,"Resume created!");
    }//GEN-LAST:event_createResumeJbtnActionPerformed

    private void browseJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseJbtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser =new JFileChooser(); 
        fileChooser.showOpenDialog(null); // Browsing image from its location 
        File chosenFile= fileChooser.getSelectedFile(); // selected file is obtained in File type object
        String selectedPath=chosenFile.getAbsolutePath(); 
        displayImagePathJLabel.setText(selectedPath); // Inline display of selected path
        resume.setImagePath(selectedPath);
        
    }//GEN-LAST:event_browseJbtnActionPerformed
    
    
    
    private void completionDateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completionDateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completionDateJTextFieldActionPerformed

    private void degreeTypeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeTypeJTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_degreeTypeJTextFieldActionPerformed

    private void majorJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majorJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_majorJTextFieldActionPerformed

    private void degreeTypeJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_degreeTypeJTextFieldFocusGained
        // TODO add your handling code here:
        degreeTypeJTextField.setText("");
    }//GEN-LAST:event_degreeTypeJTextFieldFocusGained

    private void completionDateJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_completionDateJTextFieldFocusGained
        // TODO add your handling code here:
        completionDateJTextField.setText("");
    }//GEN-LAST:event_completionDateJTextFieldFocusGained

    private void educationJLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_educationJLabelFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_educationJLabelFocusLost

    private void degreeTypeJTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_degreeTypeJTextFieldFocusLost
        // TODO add your handling code here:
        String textEntered=completionDateJTextField.getText();
        if(textEntered.equals(""))
        {
            degreeTypeJTextField.setText("(High School/Under Graduate/Graduate)..");
        }
    }//GEN-LAST:event_degreeTypeJTextFieldFocusLost
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane achievementJScrollPane;
    private javax.swing.JTextArea achievementsJTextArea;
    private javax.swing.JLabel achievementsJlabel;
    private javax.swing.JLabel addrLine1JLabel;
    private javax.swing.JTextField addrLine1TxtField;
    private javax.swing.JLabel addrLine2JLabel;
    private javax.swing.JTextField addrLine2TxtField;
    private javax.swing.JLabel addressDetailsJLabel;
    private javax.swing.JLabel affiliationJLabel;
    private javax.swing.JTextField affiliationJTextField;
    private javax.swing.JButton browseJbtn;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JTextField completionDateJTextField;
    private javax.swing.JLabel completionYearJLabel;
    private javax.swing.JLabel contactJLabel;
    private javax.swing.JTextField contactNumbTxtField;
    private javax.swing.JLabel countryJLabel;
    private javax.swing.JTextField countryTxtField;
    private javax.swing.JButton createResumeJbtn;
    private javax.swing.JLabel degreeTypeJLabel;
    private javax.swing.JTextField degreeTypeJTextField;
    private javax.swing.JLabel displayImagePathJLabel;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JTextField dobJTextField;
    private javax.swing.JLabel educationJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JLabel experienceJLabel;
    private javax.swing.JScrollPane experienceJScrollPane;
    private javax.swing.JTextArea experienceJTextArea;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JLabel gpaJLabel;
    private javax.swing.JTextField gpaJTxtField;
    private javax.swing.JLabel headerJLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JLabel majorJLabel;
    private javax.swing.JTextField majorJTextField;
    private javax.swing.JLabel objectiveJLabel;
    private javax.swing.JTextArea objectiveJtextArea;
    private javax.swing.JLabel photoUploadJLabel;
    private javax.swing.JLabel skillJLabel;
    private javax.swing.JTextField skillTxtField;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JTextField stateTxtField;
    private javax.swing.JLabel univJLabel;
    private javax.swing.JTextField univNameJTextField;
    private javax.swing.JLabel zipJLabel;
    private javax.swing.JTextField zipTxtField;
    // End of variables declaration//GEN-END:variables
}
