/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Resume;
import javax.swing.ImageIcon;
/**
 *
 * @author Ujjval
 */
public class DisplayResumeJpanel extends javax.swing.JPanel {

    /**
     * Creates new form displayResumeJpanel
     */
    public DisplayResumeJpanel(Resume recvResume) {
        initComponents();
        displayResume(recvResume);
    }
    
    private void displayResume(Resume recvdResume)
    {
        String firstName=recvdResume.getFirstName();
        firstNameTxtField.setText(firstName);
        String lastName=recvdResume.getLastName();
        lastNameTxtField.setText(lastName);
        String addLine1=recvdResume.getAddressLine1();
        addrLine1TxtField.setText(addLine1);
        String addLine2=recvdResume.getAddressLine2();
        addrLine2TxtField.setText(addLine2);
        String city=recvdResume.getCity();
        cityTxtField.setText(city);
        String state=recvdResume.getState();
        stateTxtField.setText(state);
        String country=recvdResume.getCountry();
        countryTxtField.setText(country);
        String zip=recvdResume.getZipcode();
        zipTxtField.setText(zip);
        String contactNumb=recvdResume.getContactNumb();
        contactTxtField.setText(contactNumb);
        String emailId=recvdResume.getEmailId();
        emailTxtField.setText(emailId);
        String objectiveStatement=recvdResume.getObjectiveStatement();
        objStmntjTextArea.setText(objectiveStatement);
        String affliation=recvdResume.getAffiliation();
        affiliationTxtField.setText(affliation);
        String imagePath=recvdResume.getImagePath();
        ImageIcon selectedImage=new ImageIcon(imagePath);        
        displayImageJLabel.setSize(selectedImage.getIconWidth(),selectedImage.getIconHeight());
        displayImageJLabel.setIcon(selectedImage);
        dobTxtJLabel.setText(recvdResume.getDob());
        String univName=recvdResume.getUnivName();
        universityJTextField.setText(univName);
        String dateOfCompletion=recvdResume.getDateOfCompletion();
        completionDateJTextField.setText(dateOfCompletion);
        String major=recvdResume.getMajor();
        majorJTextField.setText(major);
        String degreeType=recvdResume.getDegreeType();
        degreeTypeJTextField.setText(degreeType);
        String skillSet=recvdResume.getSkill();
        skillSetTxtField.setText(skillSet);
        String achievements=recvdResume.getAchievements();
        achievementsJTextArea.setText(achievements);
        gpaJTextField.setText(recvdResume.getGpa());
        experienceJTextArea.setText(recvdResume.getExperience());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJLabel = new javax.swing.JLabel();
        firstNameJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        addLine1JLabel = new javax.swing.JLabel();
        addLine2JLabel = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();
        countryJLabel = new javax.swing.JLabel();
        zipJLabel = new javax.swing.JLabel();
        contactJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        objStmntJLabel = new javax.swing.JLabel();
        firstNameTxtField = new javax.swing.JTextField();
        lastNameTxtField = new javax.swing.JTextField();
        addrLine1TxtField = new javax.swing.JTextField();
        addrLine2TxtField = new javax.swing.JTextField();
        cityTxtField = new javax.swing.JTextField();
        objStmntJScrollPane = new javax.swing.JScrollPane();
        objStmntjTextArea = new javax.swing.JTextArea();
        affiliationJLabel = new javax.swing.JLabel();
        affiliationTxtField = new javax.swing.JTextField();
        countryTxtField = new javax.swing.JTextField();
        zipTxtField = new javax.swing.JTextField();
        contactTxtField = new javax.swing.JTextField();
        emailTxtField = new javax.swing.JTextField();
        stateTxtField = new javax.swing.JTextField();
        displayImageJLabel = new javax.swing.JLabel();
        degreeTypeJLabel = new javax.swing.JLabel();
        educationJLabel = new javax.swing.JLabel();
        universityJLabel = new javax.swing.JLabel();
        completionDateJLabel = new javax.swing.JLabel();
        majorJLabel = new javax.swing.JLabel();
        degreeTypeJTextField = new javax.swing.JTextField();
        universityJTextField = new javax.swing.JTextField();
        completionDateJTextField = new javax.swing.JTextField();
        majorJTextField = new javax.swing.JTextField();
        skillSetJLabel = new javax.swing.JLabel();
        skillSetTxtField = new javax.swing.JTextField();
        achievementsJLabel = new javax.swing.JLabel();
        achievementsJScrollPane = new javax.swing.JScrollPane();
        achievementsJTextArea = new javax.swing.JTextArea();
        gpaJLabel = new javax.swing.JLabel();
        gpaJTextField = new javax.swing.JTextField();
        experienceJLabel = new javax.swing.JLabel();
        experienceJScrollPane = new javax.swing.JScrollPane();
        experienceJTextArea = new javax.swing.JTextArea();
        dobJLabel = new javax.swing.JLabel();
        dobTxtJLabel = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(642, 370));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerJLabel.setText("Your Resume");
        add(headerJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 11, -1, -1));

        firstNameJLabel.setText("First Name:");
        add(firstNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, 27));

        lastNameJLabel.setText("Last Name:");
        add(lastNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        addLine1JLabel.setText("Address Line1:");
        add(addLine1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, -1, -1));

        addLine2JLabel.setText("Address Line2:");
        add(addLine2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        cityJLabel.setText("City:");
        add(cityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        stateJLabel.setText("State:");
        add(stateJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        countryJLabel.setText("Country:");
        add(countryJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        zipJLabel.setText("Zip Code:");
        add(zipJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        contactJLabel.setText("Contact Number:");
        add(contactJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        emailJLabel.setText("Email Id:");
        add(emailJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        objStmntJLabel.setText("Objective Statement:");
        add(objStmntJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 50, -1, -1));

        firstNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTxtFieldActionPerformed(evt);
            }
        });
        add(firstNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 150, -1));

        lastNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTxtFieldActionPerformed(evt);
            }
        });
        add(lastNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 150, -1));
        add(addrLine1TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, -1));
        add(addrLine2TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, -1));
        add(cityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 150, -1));

        objStmntjTextArea.setColumns(20);
        objStmntjTextArea.setRows(5);
        objStmntJScrollPane.setViewportView(objStmntjTextArea);

        add(objStmntJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 70, 330, -1));

        affiliationJLabel.setText("Affiliation:");
        add(affiliationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 185, -1, -1));
        add(affiliationTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 183, 204, -1));
        add(countryTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 150, -1));
        add(zipTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 150, -1));
        add(contactTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 150, -1));
        add(emailTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 150, -1));
        add(stateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 150, -1));

        displayImageJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayImageJLabel.setOpaque(true);
        add(displayImageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 150, 160));

        degreeTypeJLabel.setText("Degree Type:");
        add(degreeTypeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 345, -1, -1));

        educationJLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Education", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        add(educationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 220, 330, 190));

        universityJLabel.setText("University:");
        add(universityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 255, -1, -1));

        completionDateJLabel.setText("Date of completion:");
        add(completionDateJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 285, -1, -1));

        majorJLabel.setText("Major:");
        add(majorJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 315, -1, -1));

        degreeTypeJTextField.setAlignmentX(1.0F);
        degreeTypeJTextField.setAlignmentY(1.0F);
        add(degreeTypeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 190, -1));

        universityJTextField.setAlignmentX(1.0F);
        universityJTextField.setAlignmentY(1.0F);
        universityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universityJTextFieldActionPerformed(evt);
            }
        });
        add(universityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 190, -1));

        completionDateJTextField.setAlignmentX(1.0F);
        completionDateJTextField.setAlignmentY(1.0F);
        add(completionDateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 190, -1));

        majorJTextField.setAlignmentX(1.0F);
        majorJTextField.setAlignmentY(1.0F);
        add(majorJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 190, -1));

        skillSetJLabel.setText("Skill Set:");
        add(skillSetJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        skillSetTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skillSetTxtFieldActionPerformed(evt);
            }
        });
        add(skillSetTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 150, -1));

        achievementsJLabel.setText("Achievements:");
        add(achievementsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        achievementsJTextArea.setColumns(20);
        achievementsJTextArea.setRows(5);
        achievementsJScrollPane.setViewportView(achievementsJTextArea);

        add(achievementsJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 330, 60));

        gpaJLabel.setText("GPA:");
        add(gpaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        gpaJTextField.setAlignmentX(1.0F);
        gpaJTextField.setAlignmentY(1.0F);
        add(gpaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 190, -1));

        experienceJLabel.setText("Experience:");
        add(experienceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 495, -1, -1));

        experienceJTextArea.setColumns(20);
        experienceJTextArea.setRows(5);
        experienceJScrollPane.setViewportView(experienceJTextArea);

        add(experienceJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 330, 60));

        dobJLabel.setText("DOB:");
        add(dobJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, -1, -1));

        dobTxtJLabel.setText("<Date will be printed>");
        add(dobTxtJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTxtFieldActionPerformed

    private void firstNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTxtFieldActionPerformed

    private void universityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_universityJTextFieldActionPerformed

    private void skillSetTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skillSetTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_skillSetTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel achievementsJLabel;
    private javax.swing.JScrollPane achievementsJScrollPane;
    private javax.swing.JTextArea achievementsJTextArea;
    private javax.swing.JLabel addLine1JLabel;
    private javax.swing.JLabel addLine2JLabel;
    private javax.swing.JTextField addrLine1TxtField;
    private javax.swing.JTextField addrLine2TxtField;
    private javax.swing.JLabel affiliationJLabel;
    private javax.swing.JTextField affiliationTxtField;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JLabel completionDateJLabel;
    private javax.swing.JTextField completionDateJTextField;
    private javax.swing.JLabel contactJLabel;
    private javax.swing.JTextField contactTxtField;
    private javax.swing.JLabel countryJLabel;
    private javax.swing.JTextField countryTxtField;
    private javax.swing.JLabel degreeTypeJLabel;
    private javax.swing.JTextField degreeTypeJTextField;
    private javax.swing.JLabel displayImageJLabel;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JLabel dobTxtJLabel;
    private javax.swing.JLabel educationJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JLabel experienceJLabel;
    private javax.swing.JScrollPane experienceJScrollPane;
    private javax.swing.JTextArea experienceJTextArea;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JLabel gpaJLabel;
    private javax.swing.JTextField gpaJTextField;
    private javax.swing.JLabel headerJLabel;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JLabel majorJLabel;
    private javax.swing.JTextField majorJTextField;
    private javax.swing.JLabel objStmntJLabel;
    private javax.swing.JScrollPane objStmntJScrollPane;
    private javax.swing.JTextArea objStmntjTextArea;
    private javax.swing.JLabel skillSetJLabel;
    private javax.swing.JTextField skillSetTxtField;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JTextField stateTxtField;
    private javax.swing.JLabel universityJLabel;
    private javax.swing.JTextField universityJTextField;
    private javax.swing.JLabel zipJLabel;
    private javax.swing.JTextField zipTxtField;
    // End of variables declaration//GEN-END:variables
}
