/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Resume;
import javax.swing.ImageIcon;

/**
 *
 * @author Ujjval
 */
public class ResumeDisplayJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ResumeDisplayJpanel
     */
    public ResumeDisplayJpanel(Resume recvdResume) {
        initComponents();        
        displayResume(recvdResume);
        
    }
    
    private void displayResume(Resume recvdResume)
    {
        String name,address;
        name=recvdResume.getFirstName()+" "+recvdResume.getLastName();
        nameDisplayJLabel.setText(name);
        address=recvdResume.getAddressLine1()+", "+recvdResume.getAddressLine2()+", ";
        address+=recvdResume.getCity()+", "+recvdResume.getState()+", "+recvdResume.getCountry();
        address+=", "+recvdResume.getZipcode()+", Contact:"+recvdResume.getContactNumb()+", Email:";
        address+=recvdResume.getEmailId();
        addressJLabel.setText(address);
        dobTxtJLabel.setText(recvdResume.getDob());
        //Image Display code Start
        objectiveTextJLabel.setText(recvdResume.getObjectiveStatement());
        experienceTxtJLabel.setText(recvdResume.getExperience());
        String imagePath=recvdResume.getImagePath();
        ImageIcon selectedImage=new ImageIcon(imagePath);        
        imageIconJLabel.setSize(selectedImage.getIconWidth(),selectedImage.getIconHeight());
        imageIconJLabel.setIcon(selectedImage);
        //Image Display code End
        univNameJLabel.setText(recvdResume.getUnivName());
        completedDateJLabel.setText(recvdResume.getDateOfCompletion());
        majorJLabel.setText(recvdResume.getMajor());
        degreeJLabel.setText(recvdResume.getDegreeType());
        gpaJLabel.setText(recvdResume.getGpa());
        skillSetTextJLabel.setText(recvdResume.getSkill());
        achievementsTextJLabel.setText(recvdResume.getAchievements());
        affiliationTxtJLabel.setText(recvdResume.getAffiliation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameDisplayJLabel = new javax.swing.JLabel();
        addressJLabel = new javax.swing.JLabel();
        imageIconJLabel = new javax.swing.JLabel();
        objectiveJLabel = new javax.swing.JLabel();
        objectiveTextJLabel = new javax.swing.JLabel();
        experienceJLabel = new javax.swing.JLabel();
        experienceTxtJLabel = new javax.swing.JLabel();
        educationJLabel = new javax.swing.JLabel();
        completedDateJLabel = new javax.swing.JLabel();
        univNameJLabel = new javax.swing.JLabel();
        majorJLabel = new javax.swing.JLabel();
        degreeJLabel = new javax.swing.JLabel();
        gpaJLabel = new javax.swing.JLabel();
        skillJLabel = new javax.swing.JLabel();
        skillSetTextJLabel = new javax.swing.JLabel();
        achievementsJLabel = new javax.swing.JLabel();
        achievementsTextJLabel = new javax.swing.JLabel();
        affiliationJLabel = new javax.swing.JLabel();
        affiliationTxtJLabel = new javax.swing.JLabel();
        dobJLabel = new javax.swing.JLabel();
        dobTxtJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        completionDateJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameDisplayJLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        nameDisplayJLabel.setForeground(new java.awt.Color(255, 0, 51));
        nameDisplayJLabel.setText("FirstName");
        add(nameDisplayJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        addressJLabel.setBackground(new java.awt.Color(0, 0, 0));
        addressJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addressJLabel.setForeground(new java.awt.Color(204, 204, 0));
        addressJLabel.setText("Address display");
        addressJLabel.setOpaque(true);
        add(addressJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 520, 20));

        imageIconJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(imageIconJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 120, 140));

        objectiveJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        objectiveJLabel.setForeground(new java.awt.Color(51, 0, 153));
        objectiveJLabel.setText("Objective:");
        add(objectiveJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        objectiveTextJLabel.setText("objectiveText");
        objectiveTextJLabel.setAutoscrolls(true);
        add(objectiveTextJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 470, 20));

        experienceJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        experienceJLabel.setForeground(new java.awt.Color(51, 0, 153));
        experienceJLabel.setText("Experience:");
        add(experienceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        experienceTxtJLabel.setText("experienceText");
        add(experienceTxtJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 340, -1));

        educationJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        educationJLabel.setForeground(new java.awt.Color(51, 0, 153));
        educationJLabel.setText("Highest Education:");
        add(educationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        completedDateJLabel.setText("CompletedDatetxt");
        add(completedDateJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        univNameJLabel.setText("UniversityName");
        add(univNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 250, -1));

        majorJLabel.setText("Major");
        add(majorJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 250, -1));

        degreeJLabel.setText("DegreeType");
        add(degreeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 250, -1));

        gpaJLabel.setText("GPA");
        add(gpaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 90, -1));

        skillJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        skillJLabel.setForeground(new java.awt.Color(51, 0, 153));
        skillJLabel.setText("Skills:");
        add(skillJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        skillSetTextJLabel.setText("SkiilSetText");
        add(skillSetTextJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 270, -1));

        achievementsJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        achievementsJLabel.setForeground(new java.awt.Color(51, 0, 153));
        achievementsJLabel.setText("Achievements:");
        add(achievementsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        achievementsTextJLabel.setText("AchievementsText");
        add(achievementsTextJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        affiliationJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        affiliationJLabel.setForeground(new java.awt.Color(51, 0, 153));
        affiliationJLabel.setText("Affiliation:");
        add(affiliationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        affiliationTxtJLabel.setText("AffiliationText");
        add(affiliationTxtJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        dobJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dobJLabel.setText("DOB:");
        add(dobJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        dobTxtJLabel.setText("dobText");
        add(dobTxtJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        jLabel1.setText("_______________________________________________________________________________________");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, 600, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 10, 420));

        completionDateJLabel.setText("Date Of Completion:");
        add(completionDateJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel achievementsJLabel;
    private javax.swing.JLabel achievementsTextJLabel;
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JLabel affiliationJLabel;
    private javax.swing.JLabel affiliationTxtJLabel;
    private javax.swing.JLabel completedDateJLabel;
    private javax.swing.JLabel completionDateJLabel;
    private javax.swing.JLabel degreeJLabel;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JLabel dobTxtJLabel;
    private javax.swing.JLabel educationJLabel;
    private javax.swing.JLabel experienceJLabel;
    private javax.swing.JLabel experienceTxtJLabel;
    private javax.swing.JLabel gpaJLabel;
    private javax.swing.JLabel imageIconJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel majorJLabel;
    private javax.swing.JLabel nameDisplayJLabel;
    private javax.swing.JLabel objectiveJLabel;
    private javax.swing.JLabel objectiveTextJLabel;
    private javax.swing.JLabel skillJLabel;
    private javax.swing.JLabel skillSetTextJLabel;
    private javax.swing.JLabel univNameJLabel;
    // End of variables declaration//GEN-END:variables
}
