/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Resume;

/**
 *
 * @author Ujjval
 */
public class ResumeMainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Resume resume;
    public ResumeMainJFrame() {
        initComponents();
        resume=new Resume();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resumeSplitPane = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        createJbtn = new javax.swing.JButton();
        displayJbtn = new javax.swing.JButton();
        formattedResumeJBtn = new javax.swing.JButton();
        displayJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createJbtn.setText("Create Resume");
        createJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJbtnActionPerformed(evt);
            }
        });

        displayJbtn.setText("Display Resume");
        displayJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayJbtnActionPerformed(evt);
            }
        });

        formattedResumeJBtn.setText("Formatted Resume");
        formattedResumeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedResumeJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanel.setLayout(controlJPanelLayout);
        controlJPanelLayout.setHorizontalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formattedResumeJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayJbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createJbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        controlJPanelLayout.setVerticalGroup(
            controlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(createJbtn)
                .addGap(28, 28, 28)
                .addComponent(displayJbtn)
                .addGap(30, 30, 30)
                .addComponent(formattedResumeJBtn)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        resumeSplitPane.setLeftComponent(controlJPanel);

        javax.swing.GroupLayout displayJPanelLayout = new javax.swing.GroupLayout(displayJPanel);
        displayJPanel.setLayout(displayJPanelLayout);
        displayJPanelLayout.setHorizontalGroup(
            displayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        displayJPanelLayout.setVerticalGroup(
            displayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        resumeSplitPane.setRightComponent(displayJPanel);

        getContentPane().add(resumeSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJbtnActionPerformed
        // TODO add your handling code here:
        CreateResumeJpanel create=new CreateResumeJpanel(resume);
        resumeSplitPane.setRightComponent(create);
    }//GEN-LAST:event_createJbtnActionPerformed

    private void displayJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayJbtnActionPerformed
        // TODO add your handling code here:
        DisplayResumeJpanel display=new DisplayResumeJpanel(resume);
        resumeSplitPane.setRightComponent(display);
    }//GEN-LAST:event_displayJbtnActionPerformed

    private void formattedResumeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedResumeJBtnActionPerformed
        // TODO add your handling code here:
        ResumeDisplayJpanel formattedDisplay=new ResumeDisplayJpanel(resume);
        resumeSplitPane.setRightComponent(formattedDisplay);
    }//GEN-LAST:event_formattedResumeJBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResumeMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResumeMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResumeMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResumeMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumeMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JButton createJbtn;
    private javax.swing.JPanel displayJPanel;
    private javax.swing.JButton displayJbtn;
    private javax.swing.JButton formattedResumeJBtn;
    private javax.swing.JSplitPane resumeSplitPane;
    // End of variables declaration//GEN-END:variables
}
