/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.ProductDirectory;
import Business.VendorDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ujjval
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private ProductDirectory prodList;
    private VendorDirectory vendorList;

    public CustomerWorkAreaJPanel(JPanel userProcessContainer, ProductDirectory prodList, VendorDirectory vendorList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.prodList = prodList;
        this.vendorList = vendorList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblProdCatalog = new javax.swing.JLabel();
        lblSelectProd = new javax.swing.JLabel();
        dropDownCategory = new javax.swing.JComboBox<>();
        btnGo = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHeader.setText("Welcome Customer");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 11, -1, -1));

        lblProdCatalog.setText("Select Product:");
        add(lblProdCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 116, -1, -1));

        lblSelectProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSelectProd.setText("Product Catalogs");
        add(lblSelectProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 80, -1, -1));

        dropDownCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SelectCategory", "Computer", "Printer", "Hardware Part", "Software" }));
        add(dropDownCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 113, -1, -1));

        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        add(btnGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 164, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        String category=dropDownCategory.getSelectedItem().toString();
        ProductsDisplayJPanel prodDisplay = new ProductsDisplayJPanel(userProcessContainer, prodList,category,vendorList);
        userProcessContainer.add("ProductDisplayJPanel", prodDisplay);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnGoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JComboBox<String> dropDownCategory;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblProdCatalog;
    private javax.swing.JLabel lblSelectProd;
    // End of variables declaration//GEN-END:variables
}
