/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Product;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ujjval
 */
public class ProductDisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductDisplayJPanel
     */
    private JPanel userProcessContainer;

    public ProductDisplayJPanel(JPanel userProcessContainer, Product p) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        txtProdName.setText(p.getName());
        txtProdModelNumb.setText(p.getModelNumber());
        lblVendorNameReplace.setText(p.getVendorName());
        txtProdBasePrice.setText(p.getBasePrice());
        txtProdDescStatement.setText(p.getDescStatemnt());
        lblProdCategoryDisp.setText(p.getCategory());
        lblProdBenefitsReplace.setText(p.getProductBenefits());
        lblProdFeaturesReplace.setText(p.getProductFeatures());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblProdName = new javax.swing.JLabel();
        lblProdModelNumb = new javax.swing.JLabel();
        lblProdVendorName = new javax.swing.JLabel();
        lblProdDescStmnt = new javax.swing.JLabel();
        lblProdBasePrice = new javax.swing.JLabel();
        lblProdFeatures = new javax.swing.JLabel();
        lblProdBenefits = new javax.swing.JLabel();
        lblProdCategory = new javax.swing.JLabel();
        lblVendorNameReplace = new javax.swing.JLabel();
        txtProdName = new javax.swing.JTextField();
        txtProdBasePrice = new javax.swing.JTextField();
        txtProdModelNumb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblProdFeaturesReplace = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblProdBenefitsReplace = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtProdDescStatement = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        lblProdCategoryDisp = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Product Display");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 11, -1, -1));

        lblProdName.setText("Product Name:");
        add(lblProdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        lblProdModelNumb.setText("Model Number:");
        add(lblProdModelNumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        lblProdVendorName.setText("Vendor Name:");
        add(lblProdVendorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        lblProdDescStmnt.setText("Product Description:");
        add(lblProdDescStmnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblProdBasePrice.setText("Base Price:");
        add(lblProdBasePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lblProdFeatures.setText("Features:");
        add(lblProdFeatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 50, -1, -1));

        lblProdBenefits.setText("Benefits:");
        add(lblProdBenefits, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 210, -1, -1));

        lblProdCategory.setText("Product Type:");
        add(lblProdCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        lblVendorNameReplace.setText("<<Vendor Name will be replaced Here>>");
        add(lblVendorNameReplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        txtProdName.setEditable(false);
        add(txtProdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 121, -1));

        txtProdBasePrice.setEditable(false);
        add(txtProdBasePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 121, -1));

        txtProdModelNumb.setEditable(false);
        add(txtProdModelNumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 121, -1));

        lblProdFeaturesReplace.setEditable(false);
        lblProdFeaturesReplace.setColumns(20);
        lblProdFeaturesReplace.setRows(5);
        jScrollPane1.setViewportView(lblProdFeaturesReplace);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 50, 205, 100));

        lblProdBenefitsReplace.setEditable(false);
        lblProdBenefitsReplace.setColumns(20);
        lblProdBenefitsReplace.setRows(5);
        jScrollPane2.setViewportView(lblProdBenefitsReplace);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 210, 205, 100));

        txtProdDescStatement.setEditable(false);
        txtProdDescStatement.setColumns(20);
        txtProdDescStatement.setRows(5);
        jScrollPane3.setViewportView(txtProdDescStatement);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 205, 69));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        lblProdCategoryDisp.setText("<<ProductCategory Displays Here>>");
        add(lblProdCategoryDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblProdBasePrice;
    private javax.swing.JLabel lblProdBenefits;
    private javax.swing.JTextArea lblProdBenefitsReplace;
    private javax.swing.JLabel lblProdCategory;
    private javax.swing.JLabel lblProdCategoryDisp;
    private javax.swing.JLabel lblProdDescStmnt;
    private javax.swing.JLabel lblProdFeatures;
    private javax.swing.JTextArea lblProdFeaturesReplace;
    private javax.swing.JLabel lblProdModelNumb;
    private javax.swing.JLabel lblProdName;
    private javax.swing.JLabel lblProdVendorName;
    private javax.swing.JLabel lblVendorNameReplace;
    private javax.swing.JTextField txtProdBasePrice;
    private javax.swing.JTextArea txtProdDescStatement;
    private javax.swing.JTextField txtProdModelNumb;
    private javax.swing.JTextField txtProdName;
    // End of variables declaration//GEN-END:variables
}
