/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.ResumeRepository;
import business.Resume;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ujjval
 */
public class ViewResumeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewResumeJPanel
     */
    private ResumeRepository resumeRepo;
    
    public ViewResumeJPanel(ResumeRepository recvdResumeRepo) {
        initComponents();
        resumeJPanel.setVisible(false);
        this.resumeRepo = recvdResumeRepo;
        populateTable();
    }
    
    private void clearFields() {
        firstNameTxtField.setText("");
        lastNameTxtField.setText("");
        addrLine1TxtField.setText("");
        addrLine2TxtField.setText("");
        cityTxtField.setText("");
        stateTxtField.setText("");
        countryTxtField.setText("");
        zipTxtField.setText("");
        contactTxtField.setText("");
        emailTxtField.setText("");
        objStmntjTextArea.setText("");
        affiliationTxtField.setText("");
        universityJTextField.setText("");
        completionDateJTextField.setText("(MM/DD/YYYY)");
        majorJTextField.setText("");
        degreeTypeJTextField.setText("(High School/Under Graduate/Graduate)..");
        gpaJTextField.setText("");
        achievementsJTextArea.setText("");
        experienceJTextArea.setText("");
        dobTxtJLabel.setText("");
        genderJLabelText.setText("");
        citizenshipJTextField.setText("");
        gradStatusTextJLabel.setText("");
        skillSetTextJLabel.setText("");
        displayImageJLabel.setIcon(null);
    }
    
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) resumesJTable.getModel();
        dtm.setRowCount(0); // Emptied the table
        for (Resume rs : resumeRepo.getResumeRepository()) {
            Object row[] = new Object[3];
            row[0] = rs;
            row[1] = rs.getLastName();
            row[2] = rs.getSkill();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerJLabel = new javax.swing.JLabel();
        resumeTableJScrollPane = new javax.swing.JScrollPane();
        resumesJTable = new javax.swing.JTable();
        panelJSeparator = new javax.swing.JSeparator();
        viewResumeJButton = new javax.swing.JButton();
        deleteResumeJButton = new javax.swing.JButton();
        resetJButton = new javax.swing.JButton();
        resumeJPanel = new javax.swing.JPanel();
        firstNameJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        addLine1JLabel = new javax.swing.JLabel();
        addLine2JLabel = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();
        countryJLabel = new javax.swing.JLabel();
        zipJLabel = new javax.swing.JLabel();
        contactJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        objStmntJLabel = new javax.swing.JLabel();
        firstNameTxtField = new javax.swing.JTextField();
        lastNameTxtField = new javax.swing.JTextField();
        addrLine1TxtField = new javax.swing.JTextField();
        addrLine2TxtField = new javax.swing.JTextField();
        cityTxtField = new javax.swing.JTextField();
        objStmntJScrollPane = new javax.swing.JScrollPane();
        objStmntjTextArea = new javax.swing.JTextArea();
        affiliationJLabel = new javax.swing.JLabel();
        affiliationTxtField = new javax.swing.JTextField();
        countryTxtField = new javax.swing.JTextField();
        zipTxtField = new javax.swing.JTextField();
        contactTxtField = new javax.swing.JTextField();
        emailTxtField = new javax.swing.JTextField();
        stateTxtField = new javax.swing.JTextField();
        displayImageJLabel = new javax.swing.JLabel();
        degreeTypeJLabel = new javax.swing.JLabel();
        educationJLabel = new javax.swing.JLabel();
        universityJLabel = new javax.swing.JLabel();
        completionDateJLabel = new javax.swing.JLabel();
        majorJLabel = new javax.swing.JLabel();
        degreeTypeJTextField = new javax.swing.JTextField();
        universityJTextField = new javax.swing.JTextField();
        completionDateJTextField = new javax.swing.JTextField();
        majorJTextField = new javax.swing.JTextField();
        skillSetJLabel = new javax.swing.JLabel();
        achievementsJLabel = new javax.swing.JLabel();
        achievementsJScrollPane = new javax.swing.JScrollPane();
        achievementsJTextArea = new javax.swing.JTextArea();
        gpaJLabel = new javax.swing.JLabel();
        gpaJTextField = new javax.swing.JTextField();
        experienceJLabel = new javax.swing.JLabel();
        experienceJScrollPane = new javax.swing.JScrollPane();
        experienceJTextArea = new javax.swing.JTextArea();
        dobJLabel = new javax.swing.JLabel();
        skillSetTextJLabel = new javax.swing.JLabel();
        genderJLabel = new javax.swing.JLabel();
        genderJLabelText = new javax.swing.JLabel();
        gradStatusJLabel = new javax.swing.JLabel();
        gradStatusTextJLabel = new javax.swing.JLabel();
        citizenshipJLabel = new javax.swing.JLabel();
        citizenshipJTextField = new javax.swing.JTextField();
        dobTxtJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerJLabel.setText("Your Available Resumes");
        add(headerJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 7, -1, -1));

        resumesJTable.setBackground(new java.awt.Color(204, 204, 204));
        resumesJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        resumesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name     ", "Last Name", "Skill Set"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resumesJTable.setGridColor(new java.awt.Color(204, 204, 204));
        resumeTableJScrollPane.setViewportView(resumesJTable);

        add(resumeTableJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 45, 500, 170));
        add(panelJSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 850, 10));

        viewResumeJButton.setText("View Resume");
        viewResumeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewResumeJButtonActionPerformed(evt);
            }
        });
        add(viewResumeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 130, -1));

        deleteResumeJButton.setText("Delete Resume");
        deleteResumeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteResumeJButtonActionPerformed(evt);
            }
        });
        add(deleteResumeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 130, -1));

        resetJButton.setText("Reset");
        resetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetJButtonActionPerformed(evt);
            }
        });
        add(resetJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 130, -1));

        resumeJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        resumeJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNameJLabel.setText("First Name:");
        resumeJPanel.add(firstNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 12, -1, 27));

        lastNameJLabel.setText("Last Name:");
        resumeJPanel.add(lastNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 52, -1, -1));

        addLine1JLabel.setText("Address Line1:");
        resumeJPanel.add(addLine1JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 162, -1, -1));

        addLine2JLabel.setText("Address Line2:");
        resumeJPanel.add(addLine2JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 192, -1, -1));

        cityJLabel.setText("City:");
        resumeJPanel.add(cityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 222, -1, -1));

        stateJLabel.setText("State:");
        resumeJPanel.add(stateJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 252, -1, -1));

        countryJLabel.setText("Country:");
        resumeJPanel.add(countryJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 292, -1, -1));

        zipJLabel.setText("Zip Code:");
        resumeJPanel.add(zipJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 352, -1, -1));

        contactJLabel.setText("Contact Number:");
        resumeJPanel.add(contactJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 382, -1, -1));

        emailJLabel.setText("Email Id:");
        resumeJPanel.add(emailJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 412, -1, -1));

        objStmntJLabel.setText("Objective Statement:");
        resumeJPanel.add(objStmntJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        firstNameTxtField.setEditable(false);
        firstNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTxtFieldActionPerformed(evt);
            }
        });
        resumeJPanel.add(firstNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 12, 150, -1));

        lastNameTxtField.setEditable(false);
        lastNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTxtFieldActionPerformed(evt);
            }
        });
        resumeJPanel.add(lastNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 52, 150, -1));

        addrLine1TxtField.setEditable(false);
        resumeJPanel.add(addrLine1TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 162, 150, -1));

        addrLine2TxtField.setEditable(false);
        resumeJPanel.add(addrLine2TxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 192, 150, -1));

        cityTxtField.setEditable(false);
        resumeJPanel.add(cityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 222, 150, -1));

        objStmntjTextArea.setEditable(false);
        objStmntjTextArea.setColumns(20);
        objStmntjTextArea.setRows(5);
        objStmntJScrollPane.setViewportView(objStmntjTextArea);

        resumeJPanel.add(objStmntJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 330, -1));

        affiliationJLabel.setText("Affiliation:");
        resumeJPanel.add(affiliationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        affiliationTxtField.setEditable(false);
        resumeJPanel.add(affiliationTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 204, -1));

        countryTxtField.setEditable(false);
        resumeJPanel.add(countryTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 292, 150, -1));

        zipTxtField.setEditable(false);
        resumeJPanel.add(zipTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 352, 150, -1));

        contactTxtField.setEditable(false);
        resumeJPanel.add(contactTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 382, 150, -1));

        emailTxtField.setEditable(false);
        resumeJPanel.add(emailTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 412, 150, -1));

        stateTxtField.setEditable(false);
        resumeJPanel.add(stateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 252, 150, -1));

        displayImageJLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayImageJLabel.setOpaque(true);
        resumeJPanel.add(displayImageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 150, 160));

        degreeTypeJLabel.setText("Degree Type:");
        resumeJPanel.add(degreeTypeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        educationJLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Education", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N
        resumeJPanel.add(educationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 330, 220));

        universityJLabel.setText("University:");
        resumeJPanel.add(universityJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 252, -1, -1));

        completionDateJLabel.setText("Date of completion:");
        resumeJPanel.add(completionDateJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 292, -1, -1));

        majorJLabel.setText("Major:");
        resumeJPanel.add(majorJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        degreeTypeJTextField.setEditable(false);
        degreeTypeJTextField.setAlignmentX(1.0F);
        degreeTypeJTextField.setAlignmentY(1.0F);
        resumeJPanel.add(degreeTypeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 190, -1));

        universityJTextField.setEditable(false);
        universityJTextField.setAlignmentX(1.0F);
        universityJTextField.setAlignmentY(1.0F);
        universityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universityJTextFieldActionPerformed(evt);
            }
        });
        resumeJPanel.add(universityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 190, -1));

        completionDateJTextField.setEditable(false);
        completionDateJTextField.setAlignmentX(1.0F);
        completionDateJTextField.setAlignmentY(1.0F);
        resumeJPanel.add(completionDateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 190, -1));

        majorJTextField.setEditable(false);
        majorJTextField.setAlignmentX(1.0F);
        majorJTextField.setAlignmentY(1.0F);
        resumeJPanel.add(majorJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 190, -1));

        skillSetJLabel.setText("Skill Set:");
        resumeJPanel.add(skillSetJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 82, -1, -1));

        achievementsJLabel.setText("Achievements:");
        resumeJPanel.add(achievementsJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 442, -1, -1));

        achievementsJTextArea.setEditable(false);
        achievementsJTextArea.setColumns(20);
        achievementsJTextArea.setRows(5);
        achievementsJScrollPane.setViewportView(achievementsJTextArea);

        resumeJPanel.add(achievementsJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 442, 330, 60));

        gpaJLabel.setText("GPA:");
        resumeJPanel.add(gpaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        gpaJTextField.setEditable(false);
        gpaJTextField.setAlignmentX(1.0F);
        gpaJTextField.setAlignmentY(1.0F);
        resumeJPanel.add(gpaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 190, -1));

        experienceJLabel.setText("Experience:");
        resumeJPanel.add(experienceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 512, -1, -1));

        experienceJTextArea.setEditable(false);
        experienceJTextArea.setColumns(20);
        experienceJTextArea.setRows(5);
        experienceJScrollPane.setViewportView(experienceJTextArea);

        resumeJPanel.add(experienceJScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 512, 330, 60));

        dobJLabel.setText("DOB:");
        resumeJPanel.add(dobJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, -1, -1));

        skillSetTextJLabel.setText("<Skills will be displayed here>");
        skillSetTextJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        resumeJPanel.add(skillSetTextJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 82, -1, 70));

        genderJLabel.setText("Gender:");
        resumeJPanel.add(genderJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        genderJLabelText.setText("<Gender Text>");
        resumeJPanel.add(genderJLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        gradStatusJLabel.setText("Graduation Status:");
        resumeJPanel.add(gradStatusJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        gradStatusTextJLabel.setText("<Grad Status Text>");
        resumeJPanel.add(gradStatusTextJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        citizenshipJLabel.setText("Citizenship:");
        resumeJPanel.add(citizenshipJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 322, -1, -1));

        citizenshipJTextField.setEditable(false);
        citizenshipJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citizenshipJTextFieldActionPerformed(evt);
            }
        });
        resumeJPanel.add(citizenshipJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 322, 150, -1));

        dobTxtJLabel.setText("<Date will be printed>");
        resumeJPanel.add(dobTxtJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

        add(resumeJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 225, 850, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTxtFieldActionPerformed

    private void lastNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTxtFieldActionPerformed

    private void universityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_universityJTextFieldActionPerformed

    private void viewResumeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewResumeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = resumesJTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            resumeJPanel.setVisible(true);
            Resume rs = (Resume) resumesJTable.getValueAt(selectedRow, 0);
            // Setting all text box values 
            String firstName = rs.getFirstName();
            firstNameTxtField.setText(firstName);
            String lastName = rs.getLastName();
            lastNameTxtField.setText(lastName);
            String addLine1 = rs.getAddressLine1();
            addrLine1TxtField.setText(addLine1);
            String addLine2 = rs.getAddressLine2();
            addrLine2TxtField.setText(addLine2);
            String city = rs.getCity();
            cityTxtField.setText(city);
            String state = rs.getState();
            stateTxtField.setText(state);
            String country = rs.getCountry();
            countryTxtField.setText(country);
            String zip = rs.getZipcode();
            zipTxtField.setText(zip);
            String contactNumb = rs.getContactNumb();
            contactTxtField.setText(contactNumb);
            String emailId = rs.getEmailId();
            emailTxtField.setText(emailId);
            String objectiveStatement = rs.getObjectiveStatement();
            objStmntjTextArea.setText(objectiveStatement);
            String affliation = rs.getAffiliation();
            affiliationTxtField.setText(affliation);
            
            String imagePath = rs.getImagePath();
            ImageIcon selectedImage = new ImageIcon(imagePath);
            Image img=selectedImage.getImage();
            Image scaledImg=img.getScaledInstance(displayImageJLabel.getWidth(),displayImageJLabel.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon scaledImage=new ImageIcon(scaledImg);
            displayImageJLabel.setIcon(scaledImage);
            
            dobTxtJLabel.setText(rs.getDob());
            String univName = rs.getUnivName();
            universityJTextField.setText(univName);
            String dateOfCompletion = rs.getDateOfCompletion();
            completionDateJTextField.setText(dateOfCompletion);
            String major = rs.getMajor();
            majorJTextField.setText(major);
            String degreeType = rs.getDegreeType();
            degreeTypeJTextField.setText(degreeType);
            String skillSet = rs.getSkill();
            skillSetTextJLabel.setText(skillSet);
            String achievements = rs.getAchievements();
            achievementsJTextArea.setText(achievements);
            gpaJTextField.setText(rs.getGpa());
            experienceJTextArea.setText(rs.getExperience());
            genderJLabelText.setText(rs.getGender());
            citizenshipJTextField.setText(rs.getCitizenship());
            gradStatusTextJLabel.setText(rs.getGraduationStatus());
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }

    }//GEN-LAST:event_viewResumeJButtonActionPerformed

    private void deleteResumeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteResumeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = resumesJTable.getSelectedRow();
        if (selectedRow >= 0) {
            int result = JOptionPane.showConfirmDialog(this, "Confirm Delete?", "Warning", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                Resume rs = (Resume) resumesJTable.getValueAt(selectedRow, 0);
                resumeRepo.deleteResumes(rs);
                JOptionPane.showMessageDialog(this, "Selected Resume has been Deleted!");
                populateTable();
                clearFields();
                resumeJPanel.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_deleteResumeJButtonActionPerformed

    private void citizenshipJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citizenshipJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citizenshipJTextFieldActionPerformed

    private void resetJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetJButtonActionPerformed
        // TODO add your handling code here:
        clearFields();
        resumeJPanel.setVisible(false);
    }//GEN-LAST:event_resetJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel achievementsJLabel;
    private javax.swing.JScrollPane achievementsJScrollPane;
    private javax.swing.JTextArea achievementsJTextArea;
    private javax.swing.JLabel addLine1JLabel;
    private javax.swing.JLabel addLine2JLabel;
    private javax.swing.JTextField addrLine1TxtField;
    private javax.swing.JTextField addrLine2TxtField;
    private javax.swing.JLabel affiliationJLabel;
    private javax.swing.JTextField affiliationTxtField;
    private javax.swing.JLabel citizenshipJLabel;
    private javax.swing.JTextField citizenshipJTextField;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JLabel completionDateJLabel;
    private javax.swing.JTextField completionDateJTextField;
    private javax.swing.JLabel contactJLabel;
    private javax.swing.JTextField contactTxtField;
    private javax.swing.JLabel countryJLabel;
    private javax.swing.JTextField countryTxtField;
    private javax.swing.JLabel degreeTypeJLabel;
    private javax.swing.JTextField degreeTypeJTextField;
    private javax.swing.JButton deleteResumeJButton;
    private javax.swing.JLabel displayImageJLabel;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JLabel dobTxtJLabel;
    private javax.swing.JLabel educationJLabel;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JLabel experienceJLabel;
    private javax.swing.JScrollPane experienceJScrollPane;
    private javax.swing.JTextArea experienceJTextArea;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JLabel genderJLabel;
    private javax.swing.JLabel genderJLabelText;
    private javax.swing.JLabel gpaJLabel;
    private javax.swing.JTextField gpaJTextField;
    private javax.swing.JLabel gradStatusJLabel;
    private javax.swing.JLabel gradStatusTextJLabel;
    private javax.swing.JLabel headerJLabel;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JLabel majorJLabel;
    private javax.swing.JTextField majorJTextField;
    private javax.swing.JLabel objStmntJLabel;
    private javax.swing.JScrollPane objStmntJScrollPane;
    private javax.swing.JTextArea objStmntjTextArea;
    private javax.swing.JSeparator panelJSeparator;
    private javax.swing.JButton resetJButton;
    private javax.swing.JPanel resumeJPanel;
    private javax.swing.JScrollPane resumeTableJScrollPane;
    private javax.swing.JTable resumesJTable;
    private javax.swing.JLabel skillSetJLabel;
    private javax.swing.JLabel skillSetTextJLabel;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JTextField stateTxtField;
    private javax.swing.JLabel universityJLabel;
    private javax.swing.JTextField universityJTextField;
    private javax.swing.JButton viewResumeJButton;
    private javax.swing.JLabel zipJLabel;
    private javax.swing.JTextField zipTxtField;
    // End of variables declaration//GEN-END:variables
}
